//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eCommerceSite.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class orderDetail
    {
        public int orderId { get; set; }
        public int pid { get; set; }
        public string name { get; set; }
        public int price { get; set; }
        public int total { get; set; }
    }
}
